theme = "solarized_light"

[editor]
bufferline = "always"
line-number = "relative"

[editor.cursor-shape]
insert = "bar"

[editor.indent-guides]
render = true
character = "â–"

[editor.statusline]
right = ["diagnostics", "selections", "register", "position", "file-encoding", "file-line-ending", "file-type"]
mode.normal = ""
mode.insert = "E> INSERT <3"
mode.select = "=== SELECT ==="

[editor.soft-wrap]
enable = true
max-wrap = 116

[editor.file-picker]
hidden = false
